baseurl = "https://travl.ml"
googleAnalytics = ""
languageCode = "en-us"
paginate = 6
summaryLength = "10"
theme = "parsa-hugo"
title = "Travel | Logs"
[[menu.main]]
hasChildren = true
name = "Homepage"
url = ""
weight = 1
[[menu.main]]
name = "Homepage 1"
parent = "Homepage"
url = "homepage/home-1"
[[menu.main]]
name = "Homepage 2"
parent = "Homepage"
url = "homepage/home-2"
[[menu.main]]
name = "About"
url = "about"
weight = 2
[[menu.main]]
name = "Contact"
url = "contact"
weight = 3
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
address = "Earth"
author = "Jane Hyde"
author_image = "images/banner-img.png"
bio = "Iâ€™m a Traveler always curious to find new places to travel and new food to try. Focusing on culture, authenticity, and hostpitality."
contact_form_action = "#"
copyright = "Copyright &copy; 2021 a theme by themefisher"
description = "A Travel blog for the curious travelers"
email = "social@travl.ml"
home = "Home"
layout = "1"
logo = "images/logo.png"
mobile = "Not Applicable"
preloader = true
search = true
[params.cookies]
enable = true
expire_days = 2
[params.instafeed]
access_token = "IGQVJYeUk4YWNIY1h4OWZANeS1wRHZARdjJ5QmdueXN2RFR6NF9iYUtfcGp1NmpxZA3RTbnU1MXpDNVBHTzZAMOFlxcGlkVHBKdjhqSnUybERhNWdQSE5hVmtXT013MEhOQVJJRGJBRURn"
enable = true
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/headroom/headroom.js"
[[params.plugins.js]]
link = "plugins/instafeed/instafeed.min.js"
[[params.plugins.js]]
link = "plugins/masonry/masonry.js"
[[params.plugins.js]]
link = "plugins/reading-time/readingTime.min.js"
[[params.plugins.js]]
link = "plugins/smooth-scroll/smooth-scroll.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[[params.social]]
icon = "ti-facebook"
link = "#"
[[params.social]]
icon = "ti-twitter-alt"
link = "#"
[[params.social]]
icon = "ti-linkedin"
link = "#"
[[params.social]]
icon = "ti-github"
link = "#"
